{{- if .Values.plugins.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: {{ .Release.Namespace }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: {{ .Values.scheduler.leaderElect }}
    profiles:
    # Compose all plugins in one profile
    - schedulerName: {{ .Values.scheduler.name }}
      plugins:
        multiPoint:
          enabled:
          - name: ShareDevPlugin
            weight: 5
        #   {{- range $.Values.plugins.enabled }}
        #   - name: {{ title . }}
        #   {{- end }}
        #   disabled:
        #   {{- range $.Values.plugins.disabled }}
        #   - name: {{ title . }}
        #   {{- end }}
        # score:
        #   enabled:
        #   - name: 'ShareDevPlugin'
        #     weight: 5
      {{- if $.Values.pluginConfig }}
      pluginConfig: {{ toYaml $.Values.pluginConfig | nindent 6 }}
      {{- end }}

  {{- /* TODO: wire CRD installation with enabled plugins. */}}
{{- end }}
