# deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
        sharedev.requests: '0.25'
        sharedev.limits: '1.0'
        sharedev.memory: '0.25'
        sharedev.vendor: 'example.com'
        sharedev.model: 'mydev'
    spec:
      schedulerName: scheduler-plugins-scheduler
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.6
