# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: scheduler-plugins-scheduler
  image: docker.io/zbsss/scheduler-plugins-kube-scheduler:latest
  replicaCount: 1
  leaderElect: false

controller:
  name: scheduler-plugins-controller
  image: docker.io/zbsss/scheduler-plugins-controller:latest
  replicaCount: 1

plugins:
  enabled: ["ShareDevPlugin"]
